
<?php
/**
 * Route table. Generated by `E:\AndroidStudioProjects\MemoriBack\generator.php` at 2020-01-22 11:10:55.
 * YOU DON'T HAVE TO MODIFY THIS FILE, JUST GENERATE IT :)
 */

$apiAuth = new \App\Api\Auth();
Flight::route('GET /auth/nonce', array($apiAuth, 'getNonce'));
Flight::route('POST /auth/login/email', array($apiAuth, 'loginByEmail'));
Flight::route('POST /auth/register/email', array($apiAuth, 'registerByEmail'));
Flight::route('POST /auth/logout', array($apiAuth, 'logout'));

$apiCalculator = new \App\Api\Calculator();
Flight::route('GET /calc/sqrt', array($apiCalculator, 'mySqrt'));

$apiWelcome = new \App\Api\Welcome();
Flight::route('GET /', array($apiWelcome, 'index'));

